name: dartify_plus
description: Dartify Plus — Essential helpers to streamline your Dart and Flutter code.

version: 0.0.1-alpha
repository: https://github.com/venhdev/dartify_plus

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.19.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
